; ============================================================
; Proyecto Final IoT - Sistema de monitoreo de cultivo
; Configuracion de PlatformIO para ESP32 (TTGO T-Beam)
; ============================================================

[env:esp32dev]
platform = espressif32
board = esp32dev          ; TTGO T-Beam funciona con el perfil generico esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    wollewald/AP3216_WE @ ^1.3.4
    mikalhart/TinyGPSPlus @ ^1.0.3

build_flags =
    -D CORE_DEBUG_LEVEL=3
