; ============================================================
; Proyecto Final IoT - Sistema de monitoreo de cultivo
; Configuracion de PlatformIO para ESP32
; ============================================================

[env:esp32dev]
platform = espressif32
board = esp32dev          ; cambia esto si tu placa es otro modelo especifico
                           ; (ej: ttgo-lora32-v1 si es una board con LoRa)
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14

build_flags =
    -D CORE_DEBUG_LEVEL=3
